name: Generate Redirects

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/data.csv'

jobs:
  generate_redirects:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate redirect pages
      run: |
        while IFS=',' read -r name url; do
          filename=$(echo "$name" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
          mkdir -p "$filename"
          cat > "$filename/index.html" << EOL
        <!DOCTYPE html>
        <html>
        <head>
          <title>$name</title>
          <meta http-equiv="refresh" content="0; URL='$url'" />
        </head>
        <body>
          <p>Redirecting to <a href="$url">$url</a>...</p>
        </body>
        </html>
        EOL
        done < ".github/workflows/data.csv"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
