name: Generate Redirects

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/data.csv'

jobs:
  generate_redirects:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate redirect pages
      run: |
        bash .github/workflows/generate_redirects.sh .github/workflows/data.csv

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
